//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IStream")]
    public interface IStream
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStream/GetLargeObject", ReplyAction="http://tempuri.org/IStream/GetLargeObjectResponse")]
        System.IO.Stream GetLargeObject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStream/GetLargeObject", ReplyAction="http://tempuri.org/IStream/GetLargeObjectResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamChannel : Service.IStream, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamClient : System.ServiceModel.ClientBase<Service.IStream>, Service.IStream
    {
        
        public StreamClient()
        {
        }
        
        public StreamClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public StreamClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StreamClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public StreamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.IO.Stream GetLargeObject()
        {
            return base.Channel.GetLargeObject();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetLargeObjectAsync()
        {
            return base.Channel.GetLargeObjectAsync();
        }
    }
}
